services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfiles/nginx.Dockerfile
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: owner@company.com
      # variable names are space-separated
      ENVSUBST_VARS: FQDN
      FQDN: terraformawsdjango.thevizironline.com

  terraformawsdjango_django:
    build:
      context: .
      dockerfile: ./Dockerfiles/django.Dockerfile
    environment:
      - DJANGO_SECRET_KEY="_a+pp^UZ&KTZNo!B+V2dDxfP!JMM5qi*1kRyD0Cem0YeePHVz6"
    ports:
      - "8000:8000"